"""Validated data capsules for Steve Build creations.

Capsules are declarative recipes generated by Steve and executed by C-Point
through approved connector engines. They are intentionally not arbitrary HTTP,
user code, or provider-specific secrets.
"""

from __future__ import annotations

import html
import json
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

from backend.services import builder_feeds

_CAPSULE_SCRIPT_RE = re.compile(
    r"<script[^>]+id=[\"']cpoint-capsule-recipes[\"'][^>]*>(.*?)</script>",
    re.I | re.S,
)
_CAPSULE_META_RE = re.compile(
    r"<meta[^>]+name=[\"']cpoint-capsule-recipes[\"'][^>]+content=[\"']([^\"']+)[\"'][^>]*>",
    re.I | re.S,
)
_NAME_RE = re.compile(r"^[a-z][a-z0-9_-]{0,39}$")
_URL_RE = re.compile(r"https?://|javascript:|data:", re.I)
_MAX_CAPSULES = 8
_MAX_PARAM_STRING = 160
_MAX_PARAMS = 12
_MAX_LIMIT = 20
_MIN_REFRESH_SECONDS = 60
_DEFAULT_REFRESH_SECONDS = 300

Recipe = Dict[str, Any]


class CapsuleValidationError(ValueError):
    """Raised when a Steve-generated capsule recipe is not executable."""


def _error(message: str) -> CapsuleValidationError:
    return CapsuleValidationError(message)


def _contains_raw_url(value: Any) -> bool:
    if isinstance(value, str):
        return bool(_URL_RE.search(value))
    if isinstance(value, list):
        return any(_contains_raw_url(v) for v in value)
    if isinstance(value, dict):
        return any(_contains_raw_url(k) or _contains_raw_url(v) for k, v in value.items())
    return False


def _clean_name(value: Any) -> str:
    name = str(value or "").strip().lower().replace(" ", "-")[:40]
    if not _NAME_RE.match(name):
        raise _error("invalid_capsule_name")
    return name


def _safe_bool(value: Any, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "y"}
    return default


def _safe_int(value: Any, *, default: int, minimum: int, maximum: int) -> int:
    try:
        n = int(value)
    except (TypeError, ValueError):
        n = default
    return max(minimum, min(n, maximum))


def _clean_params(params: Any) -> Dict[str, Any]:
    if not isinstance(params, dict):
        return {}
    out: Dict[str, Any] = {}
    for key in sorted(params.keys())[:_MAX_PARAMS]:
        k = str(key or "").strip()
        if not re.match(r"^[A-Za-z][A-Za-z0-9_-]{0,31}$", k):
            continue
        value = params[key]
        if isinstance(value, str):
            out[k] = re.sub(r"\s+", " ", value).strip()[:_MAX_PARAM_STRING]
        elif k.lower() == "limit":
            out[k] = _safe_int(value, default=8, minimum=1, maximum=_MAX_LIMIT)
        elif isinstance(value, (int, float, bool)) or value is None:
            out[k] = value
    return out


def _normalize_refresh_policy(value: Any) -> Dict[str, Any]:
    raw = value if isinstance(value, dict) else {}
    allow_manual = _safe_bool(raw.get("allow_manual"), True)
    min_interval = _safe_int(
        raw.get("min_interval_seconds"),
        default=_DEFAULT_REFRESH_SECONDS,
        minimum=_MIN_REFRESH_SECONDS,
        maximum=86400,
    )
    return {"allow_manual": allow_manual, "min_interval_seconds": min_interval}


def _normalize_one(raw: Any) -> Recipe:
    if not isinstance(raw, dict):
        raise _error("capsule_must_be_object")
    if _contains_raw_url(raw):
        raise _error("raw_urls_not_allowed")

    engine = str(raw.get("engine") or raw.get("type") or "").strip().lower()
    if engine not in {"feed", "images"}:
        raise _error("unknown_capsule_engine")

    name = _clean_name(raw.get("name") or raw.get("id") or engine)
    public = _safe_bool(raw.get("public"), False)
    refresh_policy = _normalize_refresh_policy(raw.get("refresh_policy") or raw.get("refreshPolicy"))
    title = re.sub(r"\s+", " ", str(raw.get("title") or name).strip())[:80]

    if engine == "feed":
        connector = str(raw.get("connector") or "").strip().lower()
        if connector not in builder_feeds.CONNECTORS:
            raise _error("unknown_capsule_connector")
        params = _clean_params(raw.get("params") or {})
        return {
            "schema_version": 1,
            "name": name,
            "title": title,
            "engine": "feed",
            "connector": connector,
            "params": params,
            "public": public,
            "refresh_policy": refresh_policy,
            "attribution_required": True,
        }

    params = _clean_params(raw.get("params") or {})
    query = str(raw.get("query") or params.get("q") or params.get("query") or "").strip()
    query = re.sub(r"\s+", " ", query)[:120]
    if not query:
        raise _error("image_query_required")
    limit = _safe_int(raw.get("limit") or params.get("limit"), default=8, minimum=1, maximum=_MAX_LIMIT)
    return {
        "schema_version": 1,
        "name": name,
        "title": title,
        "engine": "images",
        "query": query,
        "limit": limit,
        "public": public,
        "refresh_policy": refresh_policy,
        "attribution_required": False,
    }


def normalize_recipes(value: Any) -> List[Recipe]:
    """Validate and normalize raw recipe JSON into executable recipes."""
    if value in (None, "", []):
        return []
    if isinstance(value, str):
        value = json.loads(value)
    if isinstance(value, dict) and isinstance(value.get("capsules"), list):
        value = value["capsules"]
    if isinstance(value, dict):
        value = [value]
    if not isinstance(value, list):
        raise _error("capsules_must_be_list")
    if len(value) > _MAX_CAPSULES:
        raise _error("too_many_capsules")

    out: List[Recipe] = []
    names = set()
    for item in value:
        recipe = _normalize_one(item)
        if recipe["name"] in names:
            raise _error("duplicate_capsule_name")
        names.add(recipe["name"])
        out.append(recipe)
    return out


def dumps_recipes(recipes: List[Recipe]) -> str:
    return json.dumps(recipes or [], sort_keys=True, separators=(",", ":"))


def loads_recipes(raw: Any) -> List[Recipe]:
    try:
        return normalize_recipes(raw or [])
    except Exception:
        return []


def extract_recipes_from_html(markup: str) -> List[Recipe]:
    """Extract recipes from Steve-authored HTML sidecar tags."""
    text = markup or ""
    match = _CAPSULE_SCRIPT_RE.search(text)
    if match:
        return normalize_recipes(match.group(1).strip())
    meta = _CAPSULE_META_RE.search(text)
    if meta:
        return normalize_recipes(html.unescape(meta.group(1)).strip())
    return []


def find_recipe(recipes: List[Recipe], name: str) -> Optional[Recipe]:
    wanted = str(name or "").strip().lower()
    for recipe in recipes or []:
        if recipe.get("name") == wanted:
            return recipe
    return None


def execute_recipe(recipe: Recipe, *, refresh: bool = False) -> Dict[str, Any]:
    """Execute one validated recipe through approved engines."""
    now = datetime.utcnow().replace(microsecond=0).isoformat() + "Z"
    allow_refresh = bool((recipe.get("refresh_policy") or {}).get("allow_manual", True))
    effective_refresh = bool(refresh and allow_refresh)
    if recipe.get("engine") == "feed":
        result = builder_feeds.fetch_feed(
            str(recipe.get("connector") or ""),
            recipe.get("params") or {},
            refresh=effective_refresh,
        )
        if result.get("success"):
            result = {**result, "source": str(recipe.get("connector") or ""), "lastUpdated": now}
        return {
            **result,
            "capsule": recipe.get("name"),
            "engine": "feed",
            "refreshApplied": effective_refresh,
        }
    if recipe.get("engine") == "images":
        from backend.services import builder as builder_svc

        images = builder_svc.search_images(str(recipe.get("query") or ""), limit=int(recipe.get("limit") or 8))
        return {
            "success": True,
            "capsule": recipe.get("name"),
            "engine": "images",
            "images": images,
            "data": {"images": images},
            "attribution": "Images by Openverse",
            "source": "openverse",
            "cached": False,
            "stale": False,
            "lastUpdated": now,
            "refreshApplied": effective_refresh,
        }
    return {"success": False, "error": "unknown_capsule_engine", "data": None}
