# Google Cloud Build Configuration
# Automatically builds and deploys to Cloud Run on push to main branch

steps:
  # Step 1: Build React frontend
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd client
        npm ci
        npm run build
    id: 'build-frontend'

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cpoint-app:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cpoint-app:latest'
      - '.'
    id: 'build-docker'
    waitFor: ['build-frontend']

  # Step 3: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cpoint-app:$COMMIT_SHA'
    id: 'push-image'
    waitFor: ['build-docker']

  # Step 4: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/cpoint-app:latest'
    id: 'push-latest'
    waitFor: ['build-docker']

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cpoint-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cpoint-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'FLASK_ENV=production'
    id: 'deploy'
    waitFor: ['push-image']

# Build timeout (20 minutes should be enough)
timeout: '1200s'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/cpoint-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cpoint-app:latest'

# Substitutions (can be overridden)
substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'cpoint-app'

options:
  logging: CLOUD_LOGGING_ONLY
