"""Portuguese (pt-PT) demo content for the B2B showcase seed (see seed_b2b_demo.py).

Two communities:
  - Alumni ENA — Escola de Negócios do Atlântico  (75 membros, paid L1)
  - Corredores do Tejo                            (25 membros, free)

Nomes, empresas e escolas são fictícios.
"""

ALUMNI_COMMUNITY = {
    "key": "pt_alumni",
    "name": "Alumni ENA — Escola de Negócios do Atlântico",
    "description": (
        "A comunidade oficial de antigos alunos da Escola de Negócios do Atlântico. "
        "Oportunidades de carreira, mentoria, encontros regionais e uma rede que fica "
        "para a vida — de Lisboa a São Paulo."
    ),
    "members": 75,
    "paid_tier": "L1",
    "location": "Lisboa, Portugal",
}

RUNNING_COMMUNITY = {
    "key": "pt_running",
    "name": "Corredores do Tejo",
    "description": (
        "Clube de corrida à beira-Tejo. Longos de sábado, séries à terça, provas por todo "
        "o país e o café obrigatório no fim. Todos os ritmos são bem-vindos."
    ),
    "members": 25,
    "paid_tier": None,
    "location": "Lisboa, Portugal",
}

# (username, first, last, gender, age, city, country, role, company, industry,
#  years_exp, skills, degree, school, prev_role, prev_company, interests, bio)
AUTHORS = [
    ("ines_carvalho", "Inês", "Carvalho", "f", 33, "Lisboa", "Portugal",
     "Diretora de Estratégia", "Meridiano Consultores", "Consultoria", 10,
     "Estratégia corporativa, M&A, Facilitação de workshops", "MBA", "Escola de Negócios do Atlântico",
     "Manager", "McKinsey & Company",
     ["Vela", "Cerâmica", "Mentoria"],
     "Diretora de estratégia que ainda se entusiasma com um bom quadro branco. Curso de 2016."),
    ("miguel_fonseca", "Miguel", "Fonseca", "m", 39, "Lisboa", "Portugal",
     "VP de Engenharia", "Paylink", "Fintech", 15,
     "Liderança de engenharia, Infraestrutura de pagamentos, Recrutamento", "MSc Eng. Informática", "Escola de Negócios do Atlântico",
     "Staff Engineer", "Farfetch",
     ["Xadrez", "Futsal", "Investimento anjo"],
     "A construir infraestrutura de pagamentos na Paylink. Sempre disponível para falar de equipas de engenharia."),
    ("rita_albuquerque", "Rita", "Albuquerque", "f", 31, "Porto", "Portugal",
     "Product Lead", "SaudeViva", "Saúde Digital", 8,
     "Discovery de produto, Regulação em saúde, Investigação com utilizadores", "MBA", "Escola de Negócios do Atlântico",
     "Senior Product Manager", "Sword Health",
     ["Trail running", "Cozinha", "Podcasts"],
     "Product lead em saúde digital no Porto. MBA ENA '19. Perguntem-me sobre entrevistas de discovery."),
    ("goncalo_matos", "Gonçalo", "Matos", "m", 43, "Lisboa", "Portugal",
     "Fundador & CEO", "Almada Analytics", "Dados & IA", 18,
     "Fundação de empresas, Vendas B2B, Produtos de dados", "MBA", "Escola de Negócios do Atlântico",
     "Head of Data", "Worten Digital",
     ["Serra da Arrábida", "Vinho", "Startups early-stage"],
     "Fundador em segunda volta. A construir a Almada Analytics — inteligência de decisão para retalho."),
    ("carla_teixeira", "Carla", "Teixeira", "f", 36, "Munique", "Alemanha",
     "Diretora Financeira", "Volt Mobility", "Mobilidade", 12,
     "FP&A, Rondas de financiamento, IFRS", "MSc Finanças", "Escola de Negócios do Atlântico",
     "Senior Manager", "KPMG Deal Advisory",
     ["Piano", "Ciclismo", "Mercados de domingo"],
     "Diretora financeira numa scale-up de mobilidade em Munique. Alumna ENA, MSc Finanças."),
    ("pedro_lourenco", "Pedro", "Lourenço", "m", 29, "Lisboa", "Portugal",
     "Consultor Sénior", "Meridiano Consultores", "Consultoria", 6,
     "Due diligence, Estratégia de retalho, Modelação financeira", "MBA", "Escola de Negócios do Atlântico",
     "Analista", "EY-Parthenon",
     ["Maratonas", "Cerveja artesanal", "Fotografia"],
     "Consultor de dia, maratonista de madrugada. Curso de 2022."),
    ("beatriz_ramos", "Beatriz", "Ramos", "f", 34, "São Paulo", "Brasil",
     "Head of Growth", "Lumiar Educação", "EdTech", 9,
     "Growth loops, Marketing de ciclo de vida, Analytics", "MBA", "Escola de Negócios do Atlântico",
     "Growth Manager", "Nubank",
     ["Cerâmica", "Literatura lusófona", "Yoga"],
     "Growth na Lumiar, em São Paulo. Interessa-me educação que chega mesmo às pessoas."),
    ("tiago_neves", "Tiago", "Neves", "m", 41, "Lisboa", "Portugal",
     "Partner", "Tejo Capital", "Capital de Risco", 16,
     "Investimento Série A/B, Métricas SaaS, Conselhos de administração", "MBA", "Escola de Negócios do Atlântico",
     "Principal", "Indico Capital",
     ["Ténis", "Tascas", "Ficção científica"],
     "Partner na Tejo Capital. ENA '11. Café pago a qualquer alumni, sem exceções."),
    ("sofia_brandao", "Sofia", "Brandão", "f", 27, "Coimbra", "Portugal",
     "Gestora de Sustentabilidade", "Hortelã Verde", "Alimentação", 5,
     "Contabilidade de carbono, Cadeia de abastecimento, Certificação B Corp", "MSc Gestão", "Escola de Negócios do Atlântico",
     "Consultora", "Deloitte Sustainability",
     ["Natação em águas abertas", "Horta", "Pastelaria"],
     "A tornar as cadeias de abastecimento alimentares mais verdes. A mais nova em quase todas as reuniões, e sem problema nenhum."),
    ("antonio_maia", "António", "Maia", "m", 48, "Nova Iorque", "Estados Unidos",
     "Managing Director", "Hudson & Vale", "Banca de Investimento", 23,
     "Mercados de capitais, Cobertura TMT, Negociação", "MBA", "Escola de Negócios do Atlântico",
     "Director", "Goldman Sachs",
     ["Golfe", "Jazz", "Benfica"],
     "MD na Hudson & Vale em Nova Iorque. Curso de 2003 — sempre pronto a ajudar alumni a aterrar nos EUA."),
    ("marta_figueiredo", "Marta", "Figueiredo", "f", 30, "Amesterdão", "Países Baixos",
     "People Director", "Grachten Commerce", "E-commerce", 8,
     "Desenho organizacional, Compensação, Coaching de liderança", "MBA", "Escola de Negócios do Atlântico",
     "HR Business Partner", "Adyen",
     ["Escalada", "Mobiliário vintage", "Documentários"],
     "People director em Amesterdão. A cultura é um produto — e devíamos fazer o deploy com intenção."),
    ("joao_castel", "João", "Castelo", "m", 35, "Lisboa", "Portugal",
     "Diretor de Marketing", "Cervejaria Almirante", "Bens de Consumo", 11,
     "Estratégia de marca, Retail media, Liderança de equipas", "MBA", "Escola de Negócios do Atlântico",
     "Senior Brand Manager", "Unilever FIMA",
     ["Corrida", "Vinis", "Almoços de domingo"],
     "Construtor de marcas. ENA '16. Aos sábados de manhã estou na Ribeira das Naus, a correr."),
    # Corredores do Tejo (não-alumni)
    ("ana_severino", "Ana", "Severino", "f", 38, "Lisboa", "Portugal",
     "Fisioterapeuta", "Clínica Ribeira Fisio", "Saúde", 14,
     "Reabilitação desportiva, Análise de corrida, Treino de força", "Lic. Fisioterapia", "ESS Alcoitão",
     "Fisioterapeuta", "Hospital de Santa Maria",
     ["Maratonas", "Natação", "Cães"],
     "Capitã do clube e fisioterapeuta — trato as lesões que este clube vos dá. Maratona em 3h14."),
    ("carlos_duarte", "Carlos", "Duarte", "m", 52, "Almada", "Portugal",
     "Professor", "Escola Secundária do Monte", "Educação", 28,
     "Matemática, Treino de corrida, Milagres de horários", "Lic. Matemática", "FCUL",
     "Professor", "Escola D. Pedro V",
     ["Treinar juniores", "Imperial bem tirada", "Quizzes"],
     "Professor de matemática, treinador do clube, guardião das tabelas de ritmos. 10K em 39:50 (2008, ainda conta)."),
    ("mariana_pires", "Mariana", "Pires", "f", 26, "Lisboa", "Portugal",
     "UX Designer", "Estúdio Anfora", "Design", 4,
     "Design de interação, Design systems, Protótipos", "Lic. Design", "Faculdade de Belas-Artes",
     "Designer Júnior", "Bliss Applications",
     ["Trails", "Fotografia analógica", "Plantas"],
     "Designer que começou a correr na pandemia e nunca mais parou. A caçar um 10K abaixo dos 45."),
    ("rui_tavares", "Rui", "Tavares", "m", 45, "Oeiras", "Portugal",
     "Médico de Família", "USF Jardins do Tejo", "Saúde", 19,
     "Medicina geral e familiar, Medicina desportiva, Saúde pública", "Mestrado Integrado em Medicina", "FMUL",
     "Interno de MGF", "ULS Lisboa Ocidental",
     ["Meias maratonas", "Futebol", "Cozinha"],
     "Médico de família. Receito caminhadas e corrida. De vez em quando tomo o meu próprio remédio."),
    ("teresa_gil", "Teresa", "Gil", "f", 32, "Lisboa", "Portugal",
     "Advogada", "Sampaio & Brito", "Jurídico", 9,
     "Contratos comerciais, Proteção de dados, Negociação", "Mestrado em Direito", "Universidade Católica",
     "Associada", "PLMJ",
     ["Provas de 10K", "Coro", "Palavras cruzadas"],
     "Advogada, contralto, ex-fundo do pelotão agora orgulhosamente meio do pelotão."),
]

ALUMNI_AUTHORS = ["ines_carvalho", "miguel_fonseca", "rita_albuquerque", "goncalo_matos",
                  "carla_teixeira", "pedro_lourenco", "beatriz_ramos", "tiago_neves",
                  "sofia_brandao", "antonio_maia", "marta_figueiredo", "joao_castel"]
RUNNING_AUTHORS = ["ana_severino", "carlos_duarte", "mariana_pires", "rui_tavares",
                   "teresa_gil", "joao_castel", "pedro_lourenco"]

FILLER_FIRST_M = ["Duarte", "Francisco", "Afonso", "Martim", "Santiago", "Tomás", "Vasco",
                  "Guilherme", "Lourenço", "Rodrigo", "Diogo", "Bernardo", "Salvador", "Vicente",
                  "Henrique", "Gustavo", "Leonardo", "Frederico", "Nuno", "Filipe", "André",
                  "Bruno", "Ricardo", "Hugo", "Paulo", "Sérgio", "Marco", "Fábio", "Ivo", "Célio"]
FILLER_FIRST_F = ["Maria", "Leonor", "Matilde", "Carolina", "Francisca", "Madalena", "Constança",
                  "Margarida", "Benedita", "Lara", "Íris", "Alice", "Bianca", "Vera", "Cátia",
                  "Patrícia", "Susana", "Raquel", "Daniela", "Vanessa", "Liliana", "Sandra",
                  "Helena", "Joana", "Clara", "Eva", "Luísa", "Bárbara", "Tânia", "Sara"]
FILLER_LAST = ["Almeida", "Barbosa", "Cardoso", "Domingues", "Esteves", "Ferreira", "Gomes",
               "Henriques", "Jesus", "Leal", "Machado", "Nogueira", "Oliveira", "Pacheco",
               "Queirós", "Rebelo", "Salgado", "Torres", "Valente", "Xavier", "Azevedo",
               "Botelho", "Correia", "Dias", "Estrela", "Faria", "Guerreiro", "Lopes",
               "Meireles", "Neto", "Osório", "Pinheiro", "Ramalho", "Serra", "Teles",
               "Varela", "Abreu", "Brito", "Coutinho", "Delgado"]

ALUMNI_FILLER_ROLES = [
    ("Consultor Sénior", "Atlas Advisory", "Consultoria"),
    ("Product Manager", "Loopwire", "SaaS"),
    ("Associate de Investimento", "Foz Capital", "Private Equity"),
    ("Gestora de Marketing", "Fábula & Norte", "Media"),
    ("Diretor de Operações", "Linha Rápida Logística", "Logística"),
    ("Data Scientist", "Garça Dados", "Dados & IA"),
    ("Advogado de Empresas", "Vasconcelos & Serra", "Jurídico"),
    ("Finance Manager", "Grupo Aldeia", "Serviços Financeiros"),
    ("Fundadora", "Laboratório Campo Novo", "Startups"),
    ("Diretora de Pessoas", "Retalho Portman", "Retalho"),
    ("Account Director", "Media Milhafre", "Publicidade"),
    ("Gestor de Cadeia de Abastecimento", "Hortelã Verde", "Alimentação"),
    ("Business Developer", "Energia do Norte", "Energia"),
    ("Gestora de Programas", "Obras Cívicas", "Setor Público"),
    ("Analista de Ações", "Marlow Securities", "Gestão de Ativos"),
]
ALUMNI_FILLER_CITIES = ["Lisboa", "Porto", "Coimbra", "Braga", "Faro", "Madrid", "Paris",
                        "Londres", "Zurique", "Luanda", "São Paulo", "Genebra", "Dublin",
                        "Munique", "Macau", "Maputo"]
ALUMNI_FILLER_DEGREES = [("MBA", "Escola de Negócios do Atlântico"),
                         ("MSc Finanças", "Escola de Negócios do Atlântico"),
                         ("MSc Gestão", "Escola de Negócios do Atlântico"),
                         ("Executive MBA", "Escola de Negócios do Atlântico")]
ALUMNI_FILLER_BIOS = [
    "Alumni ENA ({year}). {role} com foco em {focus}. Sempre disponível para um café com colegas de curso.",
    "{role} na {company}. ENA {year}. Interessado em {focus} e boas conversas.",
    "Curso de {year}. A trabalhar em {focus} na {company}. Faço mentoria a estudantes de primeira geração sempre que posso.",
    "{role} · {city}. ENA {year}. Perguntem-me sobre {focus}.",
]
ALUMNI_FILLER_FOCUS = ["estratégia go-to-market", "transformação digital", "crescimento sustentável",
                       "mercados emergentes", "product-led growth", "integração pós-fusão",
                       "finanças climáticas", "insights de consumo", "excelência operacional",
                       "venture building"]

RUNNING_FILLER_ROLES = [
    ("Engenheiro de Software", "Datashift", "Tecnologia"),
    ("Enfermeira", "Hospital de São José", "Saúde"),
    ("Contabilista", "Fonseca & Melo", "Contabilidade"),
    ("Arquiteta", "Atelier Graça", "Arquitetura"),
    ("Professor do 1.º Ciclo", "EB São Vicente", "Educação"),
    ("Gerente de Café", "Café do Cais", "Restauração"),
    ("Técnica Superior", "Câmara Municipal de Lisboa", "Setor Público"),
    ("Recrutadora", "Ponte Talento", "Recrutamento"),
    ("Farmacêutico", "Farmácia Central de Alcântara", "Saúde"),
    ("Jornalista", "Gazeta Ribeirinha", "Media"),
]
RUNNING_FILLER_CITIES = ["Lisboa", "Almada", "Oeiras", "Cascais", "Loures", "Amadora",
                         "Seixal", "Vila Franca de Xira"]
RUNNING_FILLER_BIOS = [
    "{role} e corredor de fim de semana. Objetivo atual: {goal}. O café no fim é inegociável.",
    "Nos Corredores do Tejo desde {year}. {goal} em curso. {role} no resto da semana.",
    "{role} de {city}. Vim pela forma física, fiquei pelas pessoas. {goal}.",
]
RUNNING_FILLER_GOALS = ["a primeira meia maratona", "5K abaixo dos 25", "10K abaixo dos 50",
                        "uma maratona completa", "100 parkruns", "zero lesões este ano",
                        "a equipa de estafetas do clube"]

ALUMNI_THREADS = [
    {"post": {"author": "OWNER",
              "content": "Bem-vindos à nova casa da rede Alumni ENA! 🎓\n\nMudámos a comunidade para aqui para ter tudo num só sítio — discussões, mentoria, oportunidades de emprego e os encontros regionais.\n\nPara começar: deixem uma apresentação rápida nos comentários. Ano de curso, onde estão agora, e uma coisa sobre a qual os colegas vos podem perguntar.",
              "days_ago": 29},
     "hearts": 33,
     "replies": [
         {"author": "ines_carvalho", "content": "Adoro. Inês, curso de 2016, Diretora de Estratégia na Meridiano, em Lisboa. Perguntem-me tudo sobre carreiras em consultoria ou como sobreviver a um case interview.", "days_ago": 29},
         {"author": "tiago_neves", "content": "Tiago Neves, '11, Partner na Tejo Capital. Falo de bom grado sobre rondas seed e Série A — e o café é por minha conta, política antiga.", "days_ago": 29},
         {"author": "antonio_maia", "content": "Curso de 2003, MD na Hudson & Vale em Nova Iorque. Se és alumni a tentar entrar em mercados de capitais nos EUA, a minha caixa de mensagens está aberta.", "days_ago": 28},
         {"author": "sofia_brandao", "content": "Sofia, MSc Gestão '21 — sustentabilidade na Hortelã Verde, em Coimbra. Perguntem-me sobre contabilidade de carbono antes que ela vos bata à porta 😄", "days_ago": 28},
         {"author": "beatriz_ramos", "content": "Beatriz, MBA '18, growth na Lumiar em São Paulo. Também estou a organizar o encontro do capítulo Brasil — novidades em breve!", "days_ago": 28},
     ]},
    {"post": {"author": "rita_albuquerque",
              "content": "Oportunidade na SaudeViva 🏥 — estamos a contratar um(a) Senior Product Manager para a plataforma de monitorização remota (Porto ou híbrido).\n\nSérie B, impacto clínico real e uma equipa de produto que fala mesmo com utilizadores. Descrição completa na página de carreiras — ou mandem-me mensagem. Referências de alumni entram diretas para a shortlist, claro.",
              "days_ago": 26},
     "hearts": 19,
     "replies": [
         {"author": "marta_figueiredo", "content": "Vou partilhar com duas ex-colegas que encaixam na perfeição. Como é o processo?", "days_ago": 26},
         {"author": "rita_albuquerque", "content": "Chamada de triagem, case de produto (take-home, 2h no máximo, respeitamos o fim de semana), depois painel. Três semanas do início ao fim.", "days_ago": 26, "parent": 0},
         {"author": "miguel_fonseca", "content": "\"Take-home limitado a 2h\" — mais disto nos recrutamentos, por favor. 👏", "days_ago": 25},
     ]},
    {"post": {"author": "goncalo_matos",
              "content": "Update de fundador, 18 meses depois: a Almada Analytics assinou as duas primeiras cadeias de supermercados. 🎉\n\nO que gostava de ter sabido no início:\n1. O primeiro comercial contrata-se depois de TU teres fechado 10 negócios, não antes.\n2. Os compradores de retalho não compram dashboards, compram margem.\n3. A rede ENA está absurdamente subaproveitada — metade do nosso pipeline veio de introduções de alumni.\n\nSe for útil, desenvolvo qualquer um dos pontos.",
              "days_ago": 23},
     "hearts": 44,
     "replies": [
         {"author": "tiago_neves", "content": "Parabéns, Gonçalo! O ponto 1 é a lição mais cara do B2B. Quando estiveres pronto para conversar sobre a Série A, sabes onde estou.", "days_ago": 23},
         {"author": "goncalo_matos", "content": "Ah — anotado, Tiago. Falamos depois de fecharmos o Q3.", "days_ago": 23, "parent": 0},
         {"author": "ines_carvalho", "content": "Adorava um texto mais longo sobre o ponto 2. Essa formulação aplica-se também a propostas de consultoria.", "days_ago": 22},
         {"author": "carla_teixeira", "content": "O dado do pipeline por introduções é real. As nossas duas últimas contratações em finanças vieram desta rede.", "days_ago": 22},
     ]},
    {"poll": {"author": "OWNER",
              "question": "Onde deve ser o Encontro Anual de 2026? As duas cidades mais votadas recebem proposta completa da comissão de eventos.",
              "options": ["Lisboa — regresso ao campus", "Porto — o capítulo oferece-se para receber", "Madrid — central para quem está fora", "São Paulo — primeira vez do outro lado do Atlântico"],
              "days_ago": 21,
              "votes_weights": [0.40, 0.30, 0.14, 0.16]}},
    {"post": {"author": "OWNER",
              "content": "📣 Programa de Mentoria 2026 — inscrições abertas!\n\nVamos emparelhar alumni experientes com recém-graduados num ciclo de 6 meses: uma hora por mês, objetivos definidos, zero conversa fiada. No ano passado, 84% dos mentorandos disseram que o programa mudou a trajetória da carreira.\n\nMentores e mentorandos: links de inscrição nos detalhes do evento. Webinar de arranque na próxima quinta — adicionem ao calendário no separador de Eventos.",
              "days_ago": 18},
     "hearts": 28,
     "replies": [
         {"author": "antonio_maia", "content": "Inscrito como mentor outra vez. Terceiro ano seguido — a melhor hora mensal do meu calendário.", "days_ago": 18},
         {"author": "pedro_lourenco", "content": "Fui mentorando em 2023, este ano sou mentor. Ciclo completo. Façam isto, gente.", "days_ago": 17},
         {"author": "beatriz_ramos", "content": "Há hipótese de uma vertente para alumni a mudar de indústria, e não só de nível? Foi nessa transição que eu mais precisei de ajuda.", "days_ago": 17},
         {"author": "OWNER", "content": "Boa ideia, Beatriz — vou já acrescentar uma vertente de mudança de indústria ao formulário de matching.", "days_ago": 17, "parent": 2},
     ]},
    {"post": {"author": "carla_teixeira",
              "content": "Fechámos a Série C da Volt (85M€). Perguntem o que quiserem sobre levantar capital em scale-up neste mercado, visto do lado das finanças.\n\nVersão curta: a due diligence pesa 3x mais do que em 2021, os termos voltaram a ser sensatos, e o data room é a vossa primeira impressão. Respondo a perguntas concretas.",
              "days_ago": 15},
     "hearts": 37,
     "replies": [
         {"author": "goncalo_matos", "content": "Parabéns! Quanto tempo antes da ronda começaram a preparar o data room?", "days_ago": 15},
         {"author": "carla_teixeira", "content": "Seis meses. Tratámo-lo como um ativo permanente, não como artefacto da ronda — atualizado mensalmente desde então. Tornou o processo quase aborrecido.", "days_ago": 15, "parent": 0},
         {"author": "tiago_neves", "content": "Confirmo do lado do investidor: um data room limpo e atual põe-vos imediatamente no topo da pilha.", "days_ago": 14},
         {"author": "sofia_brandao", "content": "As métricas ESG apareceram na due diligence? Ouço opiniões contraditórias sobre se os fundos as pesam de verdade.", "days_ago": 14},
         {"author": "carla_teixeira", "content": "Apareceram — dois dos três term sheets tinham covenants ESG. Leves, mas reais. Partilho a lista de métricas em privado a quem quiser.", "days_ago": 14, "parent": 3},
     ]},
    {"post": {"author": "joao_castel",
              "content": "Opinião impopular ao fim de 11 anos em marca: a maioria dos 'rebrandings' é procrastinação cara.\n\nSe as vendas estão fracas, a resposta quase nunca é o logótipo. É distribuição, preço, ou o próprio produto. O rebranding dá sensação de ação enquanto se evita a conversa difícil.\n\nDiscutam comigo nos comentários (com educação, somos alumni). 😄",
              "days_ago": 12},
     "hearts": 25,
     "replies": [
         {"author": "ines_carvalho", "content": "A consultora de estratégia subscreve. A palavra 'rebranding' aparece no deck exatamente quando ninguém quer dizer 'o nosso produto perdeu'.", "days_ago": 12},
         {"author": "beatriz_ramos", "content": "Contraponto: quando reposicionámos a Lumiar de 'cursos' para 'carreiras', com o mesmo produto, a receita duplicou. Mas posicionamento ≠ logótipo — se calhar até concordamos.", "days_ago": 11},
         {"author": "joao_castel", "content": "Concordamos totalmente — reposicionar é estratégia. A parte da procrastinação é o exercício de 400 mil euros de logótipo e tipografia.", "days_ago": 11, "parent": 1},
     ]},
    {"post": {"author": "OWNER",
              "content": "Novidades dos capítulos 🌍\n\n• Lisboa: 310 membros, jantar mensal agora na Casa do Alentejo (primeira quinta-feira)\n• Porto: novo responsável de capítulo — obrigado, Rita! Arranque no dia 24\n• Brasil: a Beatriz organiza uma roundtable de edtech em São Paulo no próximo mês\n• Nova Iorque: painel de carreiras com a equipa do António em setembro\n\nQuerem abrir um capítulo na vossa cidade? Bastam cinco alumni e um espaço — do resto tratamos nós.",
              "days_ago": 9},
     "hearts": 30,
     "replies": [
         {"author": "rita_albuquerque", "content": "Porto confirmadíssimo. 30 lugares, 21 já reservados — RSVP no evento.", "days_ago": 9},
         {"author": "marta_figueiredo", "content": "Cinco alumni em Amesterdão confirmados numa única mensagem de WhatsApp. Considerem isto a nossa candidatura. 🇳🇱", "days_ago": 8},
         {"author": "OWNER", "content": "Capítulo de Amesterdão: aprovado. Foi o mais rápido de sempre — mensagem a caminho, Marta.", "days_ago": 8, "parent": 1},
     ]},
    {"post": {"author": "miguel_fonseca",
              "content": "Thread de contratações 🧵 — publiquem as vossas vagas abertas nos comentários, um comentário por empresa. Começo eu:\n\nPaylink (Lisboa/híbrido): Backend Engineer sénior (Go), SRE de plataforma, e um(a) Engineering Manager para a equipa de pagamentos. Ajudamos com vistos e a máquina de café é genuinamente excelente.",
              "days_ago": 6},
     "hearts": 22,
     "replies": [
         {"author": "rita_albuquerque", "content": "SaudeViva (Porto/híbrido): Senior PM (publicada acima — ainda aberta!), mais um(a) Clinical Data Analyst e um(a) UX Researcher.", "days_ago": 6},
         {"author": "goncalo_matos", "content": "Almada Analytics (Lisboa/remoto PT): Founding Account Executive e um(a) Senior Data Engineer. Equity que significa alguma coisa.", "days_ago": 6},
         {"author": "antonio_maia", "content": "Hudson & Vale (NYC): Associate TMT, 3-5 anos de experiência. Horários brutais, deal flow imbatível — conhecem o contrato.", "days_ago": 5},
         {"author": "carla_teixeira", "content": "Volt Mobility (Munique): FP&A Manager e um(a) Treasury Analyst. Alemão não é obrigatório, disciplina de Excel é.", "days_ago": 5},
     ]},
    {"post": {"author": "sofia_brandao",
              "content": "Pequena vitória que vale a pena partilhar: a Hortelã Verde acaba de receber a certificação B Corp, ao fim de 14 meses de trabalho. 🌱\n\nA todos os alumni que responderam às minhas perguntas em pânico pelo caminho — a auditoria à cadeia de abastecimento quase me venceu duas vezes — esta rede carregou mesmo o projeto. Vou publicar o processo todo na secção de recursos.",
              "days_ago": 4},
     "hearts": 35,
     "replies": [
         {"author": "marta_figueiredo", "content": "Enorme, Sofia! Vamos começar o processo na Grachten no próximo trimestre — esse guia vai valer ouro.", "days_ago": 4},
         {"author": "OWNER", "content": "Parabéns, Sofia — e sim, por favor, publica o guia, que eu afixo nos recursos da comunidade.", "days_ago": 3},
         {"author": "pedro_lourenco", "content": "Um cliente nosso passou por isto o ano passado; confirmo que a fase da cadeia de abastecimento é o boss final. Muito bem merecido. 👏", "days_ago": 3},
     ]},
    {"poll": {"author": "ines_carvalho",
              "question": "Próxima masterclass — a comissão de eventos contrata o orador do tema mais votado:",
              "options": ["Negociar pacotes de compensação executiva", "Ferramentas de IA para trabalho de estratégia", "O primeiro lugar num conselho de administração", "Storytelling para líderes"],
              "days_ago": 3,
              "votes_weights": [0.20, 0.40, 0.24, 0.16]}},
    {"post": {"author": "tiago_neves",
              "content": "Vou estar em Lisboa toda a próxima semana para reuniões de conselho — e fico até ao fim de semana para a gala de alumni. Quem mais vai? Vamos organizar uma mesa do capítulo de fora de Lisboa como deve ser. 🥂",
              "days_ago": 1},
     "hearts": 15,
     "replies": [
         {"author": "ines_carvalho", "content": "Vou! Mesa dos cursos de '11 a '16 ou nada feito.", "days_ago": 1},
         {"author": "miguel_fonseca", "content": "Alinhado. E devo-te um café da tua última introdução, Tiago — acabou por ser a nossa nova EM.", "days_ago": 1},
         {"author": "OWNER", "content": "120 bilhetes vendidos, restam 30 — se estão a ler isto e ainda não reservaram, o separador de Eventos está mesmo ali. 👀", "days_ago": 0},
     ]},
]

ALUMNI_FRESH_THREADS = [
    {"post": {"author": "OWNER",
              "content": "Sessão de onboarding de mentores terminada há uma hora — 38 mentores confirmados para o ciclo de 2026, a maior turma de sempre. Os resultados do matching saem na sexta-feira. 🎓",
              "days_ago": 0.13},
     "hearts": 10,
     "replies": [
         {"author": "marta_figueiredo", "content": "Foi uma sessão mesmo útil — os critérios de matching fazem muito mais sentido agora.", "days_ago": 0.09},
         {"author": "antonio_maia", "content": "38 mentores! Lembram-se de quando custava arranjar 12? Esta rede cresceu a sério.", "days_ago": 0.04},
     ]},
    {"post": {"author": "rita_albuquerque",
              "content": "Estou na plateia da HealthTech Europe e há um alumni ENA em palco, outro a moderar, e outro acabou de fazer a pergunta mais afiada do painel. Estamos em todo o lado. 😄 Mais alguém por cá hoje?",
              "days_ago": 0.33},
     "hearts": 13,
     "replies": [
         {"author": "beatriz_ramos", "content": "Ah! Estou no stand da Lumiar — apareçam, troco um café por mexericos de produto.", "days_ago": 0.28},
         {"author": "rita_albuquerque", "content": "Combinado. Vou aí depois deste painel.", "days_ago": 0.25, "parent": 0},
     ]},
]

SUB_COMMUNITIES = [
    {"key": "pt_sub_lisboa",
     "name": "Capítulo de Lisboa",
     "members": 40,
     "location": "Lisboa, Portugal",
     "description": "O braço lisboeta da rede Alumni ENA — jantares mensais na Casa do Alentejo, painéis de carreira e a ocasional humilhação no futsal.",
     "include_authors": ["ines_carvalho", "miguel_fonseca", "joao_castel", "pedro_lourenco", "tiago_neves", "goncalo_matos"],
     "threads": [
         {"post": {"author": "ines_carvalho",
                   "content": "O jantar de primeira quinta-feira está de volta à Casa do Alentejo esta semana — sala de cima reservada a partir das 19h30. Estreantes: procurem a mesa com a bandeirola da ENA e consultores a mais.",
                   "days_ago": 4},
          "hearts": 15,
          "replies": [
              {"author": "joao_castel", "content": "Levo dois colegas que estão a pensar no Executive MBA — portem-se bem, estamos a recrutar para a alma mater.", "days_ago": 4},
              {"author": "pedro_lourenco", "content": "Confirmado! E fico já com o lugar do canto antes que os da banca o apanhem.", "days_ago": 3},
          ]},
         {"post": {"author": "miguel_fonseca",
                   "content": "Pessoal de Lisboa — a Paylink tem 4 secretárias livres no escritório do Cais do Sodré até setembro. Se algum alumni estiver entre escritórios ou de passagem, são vossas. Bom café, bom wi-fi, playlist questionável.",
                   "days_ago": 2},
          "hearts": 17,
          "replies": [
              {"author": "goncalo_matos", "content": "Este é o tipo de benefício de alumni que ninguém põe na brochura. Vou aceitar a oferta para o mês que vem, Miguel.", "days_ago": 2},
              {"author": "ines_carvalho", "content": "O aviso sobre a playlist está a fazer um trabalho enorme nesta frase 😂", "days_ago": 1},
          ]},
         {"post": {"author": "pedro_lourenco",
                   "content": "Quem alinha num café antes da gala amanhã à tarde? Alguns de nós vamos estar na Fábrica Coffee Roasters da Rua das Portas de Santo Antão às 15h, antes de seguir para o Pátio da Galé. ☕",
                   "days_ago": 0.24},
          "hearts": 8,
          "replies": [
              {"author": "rita_albuquerque", "content": "O comboio chega às 14h40 — apareço, possivelmente ainda com a mala na mão.", "days_ago": 0.17},
              {"author": "joao_castel", "content": "Contem comigo. A primeira ronda de galões é por minha conta.", "days_ago": 0.07},
          ]},
     ]},
    {"key": "pt_sub_empreendedores",
     "name": "Empreendedores & Investidores",
     "members": 18,
     "location": "Global",
     "description": "Uma sala mais pequena para alumni a construir ou a investir em empresas. Clínicas de métricas mensais, post-mortems honestos e introduções que acontecem mesmo.",
     "include_authors": ["goncalo_matos", "tiago_neves", "carla_teixeira", "antonio_maia", "miguel_fonseca", "beatriz_ramos"],
     "threads": [
         {"post": {"author": "tiago_neves",
                   "content": "Clínica de métricas n.º 7, esta sexta às 13h: tragam UM número de que não gostam e trabalhamo-lo em conjunto. No mês passado, um problema de churn afinal era um problema de onboarding — resolvido numa sessão de 40 minutos. Este formato funciona.",
                   "days_ago": 5},
          "hearts": 12,
          "replies": [
              {"author": "goncalo_matos", "content": "Esse alguém era eu, e a correção entrou em produção a semana passada. Retenção +6 pontos. Tragam os vossos números feios, gente.", "days_ago": 5},
              {"author": "carla_teixeira", "content": "Apareço com uma dúvida de payback de CAC que não me deixa dormir.", "days_ago": 4},
          ]},
         {"post": {"author": "goncalo_matos",
                   "content": "Pergunta honesta para o círculo: primeira reunião de conselho depois de levantar capital — o que gostavam de ter feito de forma diferente? A nossa é daqui a três semanas e prefiro aprender com as vossas cicatrizes do que com as minhas.",
                   "days_ago": 1},
          "hearts": 10,
          "replies": [
              {"author": "tiago_neves", "content": "Enviem o deck 72 horas antes, não na véspera. Metade de uma má reunião de conselho é surpresa, não substância.", "days_ago": 1},
              {"author": "antonio_maia", "content": "Decidam o que QUEREM deles antes de entrar. Um conselho sem pedidos torna-se um conselho com opiniões.", "days_ago": 0.8},
              {"author": "carla_teixeira", "content": "Levem o CFO (ou quem for dono do modelo) para a parte dos números. Fundadores a narrar folhas de cálculo é onde a credibilidade vai morrer.", "days_ago": 0.5},
          ]},
     ]},
]

ALUMNI_EVENTS = [
    {"title": "Gala Anual de Alumni 2026",
     "days_ahead": 9, "time": "19:30", "duration_h": 5,
     "location": "Pátio da Galé, Lisboa",
     "description": "Traje formal, 150 alumni, banda ao vivo e a entrega dos prémios anuais. Inclui receção de boas-vindas e jantar de três pratos. Acompanhantes bem-vindos.",
     "rsvp_going": 36, "rsvp_maybe": 8},
    {"title": "Arranque do Programa de Mentoria (Webinar)",
     "days_ahead": 3, "time": "18:30", "duration_h": 1,
     "location": "Online — link no evento",
     "description": "Como funciona o ciclo de 2026, critérios de matching e Q&A com os pares de destaque do ano passado. Gravação disponível para quem não puder assistir em direto.",
     "rsvp_going": 49, "rsvp_maybe": 12},
    {"title": "Arranque do Capítulo do Porto",
     "days_ahead": 14, "time": "19:00", "duration_h": 3,
     "location": "Espaço Porto de Honra, Ribeira, Porto",
     "description": "Encontro de arranque do capítulo do Porto, com a Rita Albuquerque como anfitriã. Primeira rodada por conta da associação de alumni.",
     "rsvp_going": 21, "rsvp_maybe": 6},
    {"title": "Painel de Carreiras em NY: entrar na banca americana",
     "days_ahead": 27, "time": "18:30", "duration_h": 2,
     "location": "Hudson & Vale, 200 Park Ave, Nova Iorque",
     "description": "O António Maia recebe um painel com quatro alumni de banca, private equity e gestão de ativos. Dirigido a alumni até 5 anos após o curso.",
     "rsvp_going": 17, "rsvp_maybe": 5},
]

ALUMNI_LINKS = [
    {"url": "https://www.alumni-ena.example.com/mentoria", "description": "Programa de Mentoria 2026 — inscrições e critérios de matching"},
    {"url": "https://www.alumni-ena.example.com/gala", "description": "Gala Anual — bilhetes e reserva de mesas"},
    {"url": "https://www.alumni-ena.example.com/diretorio", "description": "Diretório global de alumni (entrar com o email de alumni)"},
]

RUNNING_THREADS = [
    {"post": {"author": "OWNER",
              "content": "Bem-vindos à comunidade dos Corredores do Tejo! 🏃\n\nTudo o que é do clube passa a viver aqui: planos de treino, viagens para provas, corridas sociais e as decisões importantíssimas sobre o café.\n\nRegras da casa: qualquer ritmo é um bom ritmo, ninguém fica para trás num longo, e as fotos de prova são obrigatórias por muito más que sejam.",
              "days_ago": 28},
     "hearts": 20,
     "replies": [
         {"author": "ana_severino", "content": "Adenda da capitã: 'qualquer ritmo' inclui o dia a seguir a uma maratona. Cambalear conta.", "days_ago": 28},
         {"author": "carlos_duarte", "content": "As tabelas de ritmos estão afixadas no meu frigorífico e agora também nesta comunidade. Acabaram-se as desculpas.", "days_ago": 27},
         {"author": "mariana_pires", "content": "Entrei há 8 meses sem conseguir correr 2K seguidos. Este clube foi a melhor coisa que fiz este ano. 🧡", "days_ago": 27},
     ]},
    {"post": {"author": "ana_severino",
              "content": "Longo de sábado 📋 — 7h30 no Cais do Sodré.\n\nGrupo A: 24K contínuos (semana 6 do bloco de maratona)\nGrupo B: 16K fáceis\nGrupo C: 10K social, pausas para caminhar à vontade\n\nPercurso pela margem até Belém e Algés, e volta. Paragem confirmada no Café do Cais — desta vez avisei que vínhamos todos, pedi desculpa pelo mês passado.",
              "days_ago": 24},
     "hearts": 16,
     "replies": [
         {"author": "rui_tavares", "content": "Grupo B para mim — estou de urgência às 14h, tenho de despachar até às 10.", "days_ago": 24},
         {"author": "teresa_gil", "content": "Grupo C presente. Somos o grupo que se diverte de verdade.", "days_ago": 24},
         {"author": "pedro_lourenco", "content": "24K 😅 o treino de maratona é um esquema em que me inscrevi de livre vontade. Até sábado às 7h30.", "days_ago": 23},
     ]},
    {"post": {"author": "mariana_pires",
              "content": "RELATÓRIO DE PROVA: 10K do Parque das Nações 🏁\n\n44:52!!! Sub-45 FEITO. Há oito meses o meu recorde nos 10K era 58 minutos.\n\nObrigada Carlos pela tortura das séries, Ana por me salvares o gémeo na semana 3, e a todos os que correram a última repetição comigo às terças. Nas fotos oficiais estou ou a chorar ou a morrer, possivelmente as duas coisas. Publico na mesma, regras são regras.",
              "days_ago": 20},
     "hearts": 24,
     "replies": [
         {"author": "carlos_duarte", "content": "MOMENTO DE ORGULHO DO TREINADOR. Próxima paragem: sub-43. (Tens até à primavera, está na folha de cálculo.)", "days_ago": 20},
         {"author": "ana_severino", "content": "Esse gémeo aguentou porque fizeste mesmo os exercícios aborrecidos de reabilitação. Aluna exemplar. 🌟", "days_ago": 20},
         {"author": "teresa_gil", "content": "Chorar E morrer é a única foto de prova aceitável. Parabéns, Mariana!", "days_ago": 19},
         {"author": "rui_tavares", "content": "Grande corrida! Aquele negative split na segunda metade foi de manual.", "days_ago": 19},
     ]},
    {"poll": {"author": "carlos_duarte",
              "question": "Votação do horário de verão: a que horas deve começar o longo de sábado a partir de junho?",
              "options": ["7h00 — fugir ao calor", "7h30 — está bem como está", "8h00 — é fim de semana, calma"],
              "days_ago": 16,
              "votes_weights": [0.50, 0.30, 0.20]}},
    {"post": {"author": "rui_tavares",
              "content": "Aviso de médico + corredor agora que o calor aperta: 🌡️\n\n• Hidratar ANTES do treino, não só durante\n• O grupo de WhatsApp a dizer 'está-se bem, há sombra na marginal' não é uma opinião médica\n• Tonturas ou parar de suar = parar de correr. Não é negociável.\n\nÉ isto. É este o post. Até sábado.",
              "days_ago": 13},
     "hearts": 19,
     "replies": [
         {"author": "ana_severino", "content": "Subscrito pela vossa fisioterapeuta. E já agora: os eletrólitos não são só para influencers.", "days_ago": 13},
         {"author": "carlos_duarte", "content": "Vou juntar isto à tabela de ritmos afixada, com capa plastificada. Quando é plastificado é porque é a sério.", "days_ago": 12},
     ]},
    {"post": {"author": "teresa_gil",
              "content": "Thread de sapatilhas, porque as minhas adoradas Pegasus morreram aos 812 km (RIP 🥀).\n\nCom que anda a correr esta gente? Requisitos: algum suporte para pisada pronada, aguentar o paralelepípedo e a gravilha da marginal, menos de 140€. E não, Carlos, 'as sapatilhas que já tens' não é um modelo.",
              "days_ago": 9},
     "hearts": 13,
     "replies": [
         {"author": "pedro_lourenco", "content": "Saucony Guide 17 — cumpre os três requisitos e está em promoção na loja de corrida do Saldanha, com o desconto do clube.", "days_ago": 9},
         {"author": "mariana_pires", "content": "Segundo as Guide. E o código de desconto do clube também funciona online, descobri tarde demais 😭", "days_ago": 9, "parent": 0},
         {"author": "carlos_duarte", "content": "812 km são 312 km além da minha recomendação oficial e tu SABES disso, Teresa.", "days_ago": 8},
         {"author": "teresa_gil", "content": "A plastificadora subiu-te à cabeça.", "days_ago": 8, "parent": 2},
     ]},
    {"post": {"author": "carlos_duarte",
              "content": "Novidades da pista: terças às 19h, pista do Jamor, todo o verão. 🏟️\n\nNeste bloco preparamos as estafetas de setembro: 6×800m a ritmo de 5K, recuperação completa. O grupo de iniciação faz 6×400m — a Mariana começou nesse grupo e vejam-na agora.\n\nPrimeira vez: apareçam, não é preciso inscrição. Tragam água e expectativas baixas; saem sem nenhuma das duas.",
              "days_ago": 5},
     "hearts": 17,
     "replies": [
         {"author": "mariana_pires", "content": "Confirmo que o grupo de iniciação é onde a magia começa. E 'saem sem nenhuma das duas' 😂", "days_ago": 5},
         {"author": "joao_castel", "content": "Finalmente voltei a ter as terças livres — contem comigo para os 800. Tenham piedade.", "days_ago": 4},
         {"author": "carlos_duarte", "content": "Piedade não faz parte do plano de treino. Bem-vindo de volta, João.", "days_ago": 4, "parent": 1},
     ]},
    {"poll": {"author": "ana_severino",
              "question": "Viagem do clube: para que meia maratona de outono reservamos a carrinha?",
              "options": ["Meia do Porto — ambiente incrível", "Meia de Coimbra — plana e rápida", "Meia do Algarve — prova + praia", "Meia de Lisboa — dormimos na nossa cama"],
              "days_ago": 3,
              "votes_weights": [0.35, 0.18, 0.29, 0.18]}},
    {"post": {"author": "OWNER",
              "content": "Administração do clube, versão divertida 📊\n\nPassámos os 25 membros este mês — bem-vindos a todos os que entraram depois da feira de verão! Algumas notas:\n\n• As quotas mantêm-se nos 3€/mês, que continuam a financiar sobretudo os bolos de arroz do fim do treino\n• Treino de boas-vindas aos novos membros: este sábado, Grupo C, liderado por mim\n• A folha das equipas de estafetas de setembro sai para a semana — o Carlos manda dizer 'comecem a fazer os vossos 800'\n\nÉ bom ter-vos aqui. 🧡",
              "days_ago": 1},
     "hearts": 18,
     "replies": [
         {"author": "ana_severino", "content": "Bem-vindos, novatos! Procurem-me se alguma coisa doer — de preferência antes de ficar interessante.", "days_ago": 1},
         {"author": "teresa_gil", "content": "A transparência no orçamento dos bolos de arroz é a razão pela qual confio na direção deste clube.", "days_ago": 0},
     ]},
]

RUNNING_FRESH_THREADS = [
    {"post": {"author": "ana_severino",
              "content": "Treino matinal feito, reconhecimento do percurso concluído: o longo de sábado passa a incluir o troço NOVO da ciclovia junto à doca — pavimento acabado de refazer, zero gravilha parte-tornozelos. Pequenas alegrias. 🏃‍♀️",
              "days_ago": 0.27},
     "hearts": 9,
     "replies": [
         {"author": "teresa_gil", "content": "A gravilha a reclamar a sua última vítima (eu, duas vezes) é o fim de uma era.", "days_ago": 0.19},
         {"author": "carlos_duarte", "content": "Vou atualizar o mapa do percurso logo à noite. Plastificado, obviamente.", "days_ago": 0.09},
     ]},
]

RUNNING_EVENTS = [
    {"title": "Longo de Sábado — Cais do Sodré",
     "days_ahead": 2, "time": "07:30", "duration_h": 2,
     "location": "Cais do Sodré, Lisboa",
     "description": "Grupos A (24K), B (16K) e C (10K social). Paragem no Café do Cais no regresso. Novos membros: Grupo C, o Paulo lidera.",
     "rsvp_going": 15, "rsvp_maybe": 5},
    {"title": "Treino de Pista — Jamor",
     "days_ahead": 4, "time": "19:00", "duration_h": 1,
     "location": "Pista do Jamor, Oeiras",
     "description": "6×800m a ritmo de 5K (iniciação: 6×400m). Sem inscrição, tragam água.",
     "rsvp_going": 11, "rsvp_maybe": 4},
    {"title": "Estafetas do Clube",
     "days_ahead": 24, "time": "10:00", "duration_h": 4,
     "location": "Parque Florestal de Monsanto",
     "description": "Equipas de 4 × 5K. A folha das equipas sai para a semana — subornar o treinador com bolos de arroz é incentivado mas ineficaz.",
     "rsvp_going": 13, "rsvp_maybe": 6},
]

RUNNING_LINKS = [
    {"url": "https://www.corredoresdotejo.example.com/tabelas-de-ritmos", "description": "Tabelas de ritmos oficiais do Carlos (edição plastificada)"},
    {"url": "https://www.corredoresdotejo.example.com/quotas", "description": "Quotas e inscrição — 3€/mês"},
]
